class: stacierl.agent.synchron.Synchron
_id: 139891083861440
algo:
  class: stacierl.algo.sac.SAC
  _id: 139893428029568
  model:
    class: stacierl.algo.sacmodel.inputembedder.InputEmbedding
    _id: 139893428028176
    lr_alpha: 0.0003
    q1:
      class: stacierl.network.qnetwork.QNetwork
      _id: 139893411703248
      n_observations: 600
      n_actions: 2
      hidden_layers:
      - 700
      - 600
      - 500
      init_w: 0.003
    q2:
      class: stacierl.network.qnetwork.QNetwork
      _id: 139893436510800
      n_observations: 600
      n_actions: 2
      hidden_layers:
      - 700
      - 600
      - 500
      init_w: 0.003
    policy:
      class: stacierl.network.gaussianpolicy.GaussianPolicy
      _id: 139893428029136
      n_observations: 600
      n_actions: 2
      hidden_layers:
      - 700
      - 600
      - 500
      init_w: 0.003
      log_std_min: -20
      log_std_max: 2
    q1_optimizer:
      class: stacierl.optimizer.optimizer.Adam
      _id: 139893436510416
      lr: 0.0003
      betas: &id001 !!python/tuple
      - 0.9
      - 0.999
      eps: 1.0e-08
      weight_decay: 0
      amsgrad: false
      network:
        class: stacierl.network.qnetwork.QNetwork
        _id: 139893411703248
    q2_optimizer:
      class: stacierl.optimizer.optimizer.Adam
      _id: 139893442581888
      lr: 0.0003
      betas: *id001
      eps: 1.0e-08
      weight_decay: 0
      amsgrad: false
      network:
        class: stacierl.network.qnetwork.QNetwork
        _id: 139893436510800
    policy_optimizer:
      class: stacierl.optimizer.optimizer.Adam
      _id: 139893428030336
      lr: 0.0003
      betas: *id001
      eps: 1.0e-08
      weight_decay: 0
      amsgrad: false
      network:
        class: stacierl.network.gaussianpolicy.GaussianPolicy
        _id: 139893428029136
    q1_common_input_embedder:
      class: stacierl.algo.sacmodel.inputembedder.Embedder
      _id: 139893428027792
      network:
        class: stacierl.network.lstm.LSTM
        _id: 139893441799936
        n_inputs: 12
        n_layer: 1
        n_nodes: 600
      update: true
      optimizer:
        class: stacierl.optimizer.optimizer.Adam
        _id: 139893441799456
        lr: 0.0003
        betas: *id001
        eps: 1.0e-08
        weight_decay: 0
        amsgrad: false
        network:
          class: stacierl.network.lstm.LSTM
          _id: 139893441799936
    q2_common_input_embedder:
      class: stacierl.algo.sacmodel.inputembedder.Embedder
      _id: 139893428029328
      network:
        class: stacierl.network.lstm.LSTM
        _id: 139893441799936
      update: false
      optimizer: null
      scheduler: null
    policy_common_input_embedder:
      class: stacierl.algo.sacmodel.inputembedder.Embedder
      _id: 139893428027840
      network:
        class: stacierl.network.lstm.LSTM
        _id: 139893441799936
      update: false
      optimizer: null
      scheduler: null
  n_actions: 2
  gamma: 0.99
  tau: 0.005
  reward_scaling: 1
  action_scaling: 1
  exploration_action_noise: 0.25
env_train:
  class: eve.env.Env
  _id: 139887691390544
  vessel_tree:
    class: stacievesseltrees.aorticarch.AorticArch
    _id: 139895507762960
    arch_type: VII
    seed: null
    rotate_z: 20
    rotate_x: -5
    omit_y_axis: true
  intervention:
    class: eve.simulation3d.guidewiremp.GuidewireMP
    _id: 139893411813504
    vessel_tree:
      class: stacievesseltrees.aorticarch.AorticArch
      _id: 139895507762960
    device:
      class: eve.simulation3d.device.jwire.JWire
      _id: 139887691390784
      name: guidewire
      velocity_limit: &id002 !!python/tuple
      - 50
      - 3.14
      total_length: 450
      tip_length: 15.2
      tip_angle: 1.2566370614359172
      tip_outer_diameter: 0.7
      tip_inner_diameter: 0.0
      straight_outer_diameter: 0.89
      straight_inner_diameter: 0.0
      poisson_ratio: 0.49
      young_modulus_tip: 17000.0
      young_modulus_straight: 80000.0
      mass_density_tip: 2.1e-05
      mass_density_straight: 2.1e-05
      visu_edges_per_mm: 0.5
      collis_edges_per_mm_tip: 2
      collis_edges_per_mm_straight: 0.1
      beams_per_mm_tip: 1.4
      beams_per_mm_straight: 0.09
      color:
      - 0.0
      - 0.0
      - 0.0
    stop_device_at_tree_end: true
    image_frequency: 7.5
    dt_simulation: 0.006
    sofa_native_gui: false
    step_timeout: 10
    sofa_restart_episodes: 25
    tracking_low_custom:
    - -102.74128723144531
    - -13.090737342834473
    - -6.674828052520752
    tracking_high_custom:
    - 69.3172378540039
    - 13.090737342834473
    - 307.8525695800781
  start:
    class: eve.start.maxdevicelength.MaxDeviceLength
    _id: 139893411696208
    intervention:
      class: eve.simulation3d.guidewiremp.GuidewireMP
      _id: 139893411813504
    max_length: 380
  target:
    class: eve.target.centerlinerandom.CenterlineRandom
    _id: 139893411813456
    vessel_tree:
      class: stacievesseltrees.aorticarch.AorticArch
      _id: 139895507762960
    intervention:
      class: eve.simulation3d.guidewiremp.GuidewireMP
      _id: 139893411813504
    threshold: 5
    branches:
    - right subclavian artery
    - right common carotid artery
    - left common carotid artery
    - left subclavian artery
    - brachiocephalic trunk
    - common origin
    min_distance_between_possible_targets: null
  success:
    class: eve.success.targetreached.TargetReached
    _id: 139893442014320
    target:
      class: eve.target.centerlinerandom.CenterlineRandom
      _id: 139893411813456
  state:
    class: eve.state.combination.Combination
    _id: 139893441939296
    states:
    - class: eve.state.wrapper.memory.Memory
      _id: 139893417358960
      wrapped_state:
        class: eve.state.wrapper.normalize.Normalize
        _id: 139893442025600
        wrapped_state:
          class: eve.state.wrapper.coordinatesto2d.CoordinatesTo2D
          _id: 139893442025312
          wrapped_state:
            class: eve.state.tracking.Tracking
            _id: 139893441818288
            intervention:
              class: eve.simulation3d.guidewiremp.GuidewireMP
              _id: 139893411813504
            n_points: 2
            resolution: 1.0
            name: tracking
          dimension_to_delete: y
          name: tracking
        name: tracking
      n_steps: 2
      reset_mode: 0
      name: tracking
    - class: eve.state.wrapper.normalize.Normalize
      _id: 139893441835360
      wrapped_state:
        class: eve.state.wrapper.coordinatesto2d.CoordinatesTo2D
        _id: 139893417358576
        wrapped_state:
          class: eve.state.target.Target
          _id: 139893417360400
          target:
            class: eve.target.centerlinerandom.CenterlineRandom
            _id: 139893411813456
          name: target
        dimension_to_delete: y
        name: target
      name: target
    - class: eve.state.wrapper.normalize.Normalize
      _id: 139893441835168
      wrapped_state:
        class: eve.state.lastaction.LastAction
        _id: 139893441838576
        intervention:
          class: eve.simulation3d.guidewiremp.GuidewireMP
          _id: 139893411813504
        name: last_action
      name: last_action
    name: state_combination
  reward:
    class: eve.reward.combination.Combination
    _id: 139893436307440
    rewards:
    - class: eve.reward.targetreached.TargetReached
      _id: 139893441938000
      target:
        class: eve.target.centerlinerandom.CenterlineRandom
        _id: 139893411813456
      factor: 1.0
    - class: eve.reward.step.Step
      _id: 139893441938096
      factor: -0.005
    - class: eve.reward.pathlengthdelta.PathLengthDelta
      _id: 139893436307152
      pathfinder:
        class: eve.pathfinder.bruteforcebfs.BruteForceBFS
        _id: 139893411696304
        vessel_tree:
          class: stacievesseltrees.aorticarch.AorticArch
          _id: 139895507762960
        intervention:
          class: eve.simulation3d.guidewiremp.GuidewireMP
          _id: 139893411813504
        target:
          class: eve.target.centerlinerandom.CenterlineRandom
          _id: 139893411813456
      factor: 0.001
  done:
    class: eve.done.combination.Combination
    _id: 139893442386816
    dones:
    - class: eve.done.targetreached.TargetReached
      _id: 139893442387536
      target:
        class: eve.target.centerlinerandom.CenterlineRandom
        _id: 139893411813456
    - class: eve.done.maxsteps.MaxSteps
      _id: 139893442385808
      max_steps: 150
  info:
    class: eve.info.dummy.Dummy
    _id: 139895507759456
  imaging:
    class: eve.imaging.dummy.Dummy
    _id: 139893441817088
  pathfinder:
    class: eve.pathfinder.bruteforcebfs.BruteForceBFS
    _id: 139893411696304
  interim_target:
    class: eve.interimtarget.dummy.Dummy
    _id: 139887560307664
  visualisation:
    class: eve.visualisation.dummy.Dummy
    _id: 139893442014800
  vessel_tree_randomizer:
    class: lnk_training.ijcars23.randomizer.IJCARS23Randomizer
    _id: 139893442014464
    vessel_tree:
      class: stacievesseltrees.aorticarch.AorticArch
      _id: 139895507762960
    intervention:
      class: eve.simulation3d.guidewiremp.GuidewireMP
      _id: 139893411813504
    mode: train
    neglected_archtypes: null
    n_vesselseeds: null
    scaling_range:
    - 0.7
    - 1.3
    second_scaling_range: null
    diameter_scaling_range:
    - 0.6
    - 0.6
    seed: null
env_eval:
  class: eve.env.Env
  _id: 139893411696544
  vessel_tree:
    class: stacievesseltrees.aorticarch.AorticArch
    _id: 139893441839008
    arch_type: VII
    seed: null
    rotate_z: 20
    rotate_x: -5
    omit_y_axis: true
  intervention:
    class: eve.simulation3d.guidewiremp.GuidewireMP
    _id: 139893436528096
    vessel_tree:
      class: stacievesseltrees.aorticarch.AorticArch
      _id: 139893441839008
    device:
      class: eve.simulation3d.device.jwire.JWire
      _id: 139893436527232
      name: guidewire
      velocity_limit: *id002
      total_length: 450
      tip_length: 15.2
      tip_angle: 1.2566370614359172
      tip_outer_diameter: 0.7
      tip_inner_diameter: 0.0
      straight_outer_diameter: 0.89
      straight_inner_diameter: 0.0
      poisson_ratio: 0.49
      young_modulus_tip: 17000.0
      young_modulus_straight: 80000.0
      mass_density_tip: 2.1e-05
      mass_density_straight: 2.1e-05
      visu_edges_per_mm: 0.5
      collis_edges_per_mm_tip: 2
      collis_edges_per_mm_straight: 0.1
      beams_per_mm_tip: 1.4
      beams_per_mm_straight: 0.09
      color:
      - 0.0
      - 0.0
      - 0.0
    stop_device_at_tree_end: true
    image_frequency: 7.5
    dt_simulation: 0.006
    sofa_native_gui: false
    step_timeout: 10
    sofa_restart_episodes: 25
    tracking_low_custom:
    - -101.91620635986328
    - -12.907462120056152
    - -6.728710174560547
    tracking_high_custom:
    - 70.66748046875
    - 12.907462120056152
    - 307.16986083984375
  start:
    class: eve.start.maxdevicelength.MaxDeviceLength
    _id: 139893442014272
    intervention:
      class: eve.simulation3d.guidewiremp.GuidewireMP
      _id: 139893436528096
    max_length: 380
  target:
    class: eve.target.centerlinerandom.CenterlineRandom
    _id: 139893442014512
    vessel_tree:
      class: stacievesseltrees.aorticarch.AorticArch
      _id: 139893441839008
    intervention:
      class: eve.simulation3d.guidewiremp.GuidewireMP
      _id: 139893436528096
    threshold: 5
    branches:
    - right subclavian artery
    - right common carotid artery
    - left common carotid artery
    - left subclavian artery
    - brachiocephalic trunk
    - common origin
    min_distance_between_possible_targets: null
  success:
    class: eve.success.targetreached.TargetReached
    _id: 139893411703584
    target:
      class: eve.target.centerlinerandom.CenterlineRandom
      _id: 139893442014512
  state:
    class: eve.state.combination.Combination
    _id: 139893441975296
    states:
    - class: eve.state.wrapper.memory.Memory
      _id: 139893442584384
      wrapped_state:
        class: eve.state.wrapper.normalize.Normalize
        _id: 139893442582080
        wrapped_state:
          class: eve.state.wrapper.coordinatesto2d.CoordinatesTo2D
          _id: 139893442581408
          wrapped_state:
            class: eve.state.tracking.Tracking
            _id: 139893441994816
            intervention:
              class: eve.simulation3d.guidewiremp.GuidewireMP
              _id: 139893436528096
            n_points: 2
            resolution: 1.0
            name: tracking
          dimension_to_delete: y
          name: tracking
        name: tracking
      n_steps: 2
      reset_mode: 0
      name: tracking
    - class: eve.state.wrapper.normalize.Normalize
      _id: 139893442582896
      wrapped_state:
        class: eve.state.wrapper.coordinatesto2d.CoordinatesTo2D
        _id: 139893442582608
        wrapped_state:
          class: eve.state.target.Target
          _id: 139893442581504
          target:
            class: eve.target.centerlinerandom.CenterlineRandom
            _id: 139893442014512
          name: target
        dimension_to_delete: y
        name: target
      name: target
    - class: eve.state.wrapper.normalize.Normalize
      _id: 139893442582032
      wrapped_state:
        class: eve.state.lastaction.LastAction
        _id: 139893442582320
        intervention:
          class: eve.simulation3d.guidewiremp.GuidewireMP
          _id: 139893436528096
        name: last_action
      name: last_action
    name: state_combination
  reward:
    class: eve.reward.combination.Combination
    _id: 139893441974576
    rewards:
    - class: eve.reward.targetreached.TargetReached
      _id: 139893441977600
      target:
        class: eve.target.centerlinerandom.CenterlineRandom
        _id: 139893442014512
      factor: 1.0
    - class: eve.reward.step.Step
      _id: 139893441976160
      factor: -0.005
    - class: eve.reward.pathlengthdelta.PathLengthDelta
      _id: 139893441975536
      pathfinder:
        class: eve.pathfinder.bruteforcebfs.BruteForceBFS
        _id: 139893442014032
        vessel_tree:
          class: stacievesseltrees.aorticarch.AorticArch
          _id: 139893441839008
        intervention:
          class: eve.simulation3d.guidewiremp.GuidewireMP
          _id: 139893436528096
        target:
          class: eve.target.centerlinerandom.CenterlineRandom
          _id: 139893442014512
      factor: 0.001
  done:
    class: eve.done.combination.Combination
    _id: 139893441977792
    dones:
    - class: eve.done.targetreached.TargetReached
      _id: 139893441977408
      target:
        class: eve.target.centerlinerandom.CenterlineRandom
        _id: 139893442014512
    - class: eve.done.maxsteps.MaxSteps
      _id: 139893441978176
      max_steps: 150
  info:
    class: eve.info.dummy.Dummy
    _id: 139893436527280
  imaging:
    class: eve.imaging.dummy.Dummy
    _id: 139893441838336
  pathfinder:
    class: eve.pathfinder.bruteforcebfs.BruteForceBFS
    _id: 139893442014032
  interim_target:
    class: eve.interimtarget.dummy.Dummy
    _id: 139893441800368
  visualisation:
    class: eve.visualisation.dummy.Dummy
    _id: 139893411702192
  vessel_tree_randomizer:
    class: lnk_training.ijcars23.randomizer.IJCARS23Randomizer
    _id: 139893411702432
    vessel_tree:
      class: stacievesseltrees.aorticarch.AorticArch
      _id: 139893441839008
    intervention:
      class: eve.simulation3d.guidewiremp.GuidewireMP
      _id: 139893436528096
    mode: eval
    neglected_archtypes: null
    n_vesselseeds: null
    scaling_range:
    - 0.7
    - 1.3
    second_scaling_range: null
    diameter_scaling_range:
    - 0.6
    - 0.6
    seed: null
replay_buffer:
  class: stacierl.replaybuffer.vanillashared.VanillaEpisodeShared
  _id: 139893428029712
  capacity: 10000.0
  batch_size: 8
n_worker: 25
n_trainer: 4
worker_device: cpu
trainer_device: cuda:0
consecutive_action_steps: 1
normalize_actions: true
share_trainer_model: false
